//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBase.Domain.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostDetail
    {
        public int ID { get; set; }
        public string PostedContent { get; set; }
        public byte[] PostedImage { get; set; }
        public byte[] PostedFile { get; set; }
    
        public virtual Post Post { get; set; }
    }
}
